language: python

python:
  - 2.6
  - 2.7
  - pypy

install:  # requirements.txt doesn't respect order?
  - pip install -q simplejson --use-mirrors
  - pip install -q Twisted --use-mirrors
  - pip install -q git+git://github.com/fiorix/cyclone.git --use-mirrors

script:
  - trial tests
